#!/bin/bash
apt-get install python python-pip python-tk libopencv-video-dev

# Python packages
pip install scipy 
pip install opencv-python
pip install matplotlib
pip install scikit-learn

# Upgrade all packages
pip install -U 
